services:
  grafana:
    image: grafana.grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"

  alloy:
    image: alloy/alloy
    ports:
      - "8081:8081"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8080:8080"